language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
#  - export PIP_INDEX_URL=https://simple.crate.io/
#  - sudo apt-get update
install:
  - pip install -e .
  - pip install Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
branches:
  only:
    - develop
